services:

  lab:
    build:
      context: .
    command: /opt/bin/run.sh lab
    shm_size: '2gb'
    volumes:
      - ./app:/app
      - ~/.cache/huggingface:/cache/huggingface
      - ~/.cache/fastai:/cache/fastai
    ports:
      - "8989:8989"
    environment:
      - HOST_USER_ID
      - HOST_GROUP_ID
      - CACHE_DIR=/cache
      - HF_HOME=/cache/huggingface
      - FASTAI_HOME=/cache/fastai
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
